# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="§oAll rights reserved"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://discord.gg/apocraft" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="apomod" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="0.0.1" #mandatory
 # A display name for the mod
displayName="§4§lApo Mod" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://apocraft.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
credits="§lMod made by the §o\"Apocraft Dev Team (ADT)\"§r§l for the §4§lApocraft§r§l Roleplay server." #optional
# A text field displayed in the mod UI
authors="§lV_E_L_D" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Core mod with every components for the server, blocks, items, crafts, thirst, heat, cold, biomes...

§r§lNEW STUFF
BIOMES:§r
    §r- §oEternal Cold Night§r
    §r- §oHellfire World§r
    §r- §oParadisus Ring§r

§r§lBLOCKS:§r
    §r- §oSandbags blocks§r
    §r- §oBarrier blocks§r
    §r- §oVent blocks§r
    §r- §oArtisanale Table (An advanced crafting table)§r

§r§lITEMS:§r
    §r- §oM16A4 (Assault Rifle)§r
    §r- §oRPG-9 (Rocket Launcher)§r
    §r- §oApo Cola (Soda, +2 of thirst-bar)§r
    §r- §oPolar outfit (Make the player more resistant to cold but make the temperature easily up very high at normal temperature | Attenuates 75% of the cold)§r
    §r- §oDesert outfit (Make the player more resistant to heat but make the temperature cold when at normal temperature | Attenuates 40% of the heatness)§r

§r§lFUNCTIONS:§r
    §r- §oThirstness (0 to 20, can make the player die, very slow damage rate (120 seconds = 1HP))§r
    §r- §oTemperature (from -70 to +70 degrees Celsius | Cold make the player slow and hungry very speedly, hot make player slow and very thirsty (exponential))§r
    §r- §oPain (From 0 to 10 | Higher values make health of player down, lower values make him loss some capacities like run, jump, punch, etc...)§r


§r§lEDITED STUFF
BLOCKS:§r
    §r- §oCraft table (Doesn't open a crafting menu anymore)§r

§r§lITEMS:§r
    §r- §oWater bottle (Water, can be reloaded by right-clicking on river water (river biome), + 4 of thirst)§r

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.apomod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[36,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.apomod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17,1.18)"
    ordering="NONE"
    side="BOTH"
